-- fd . src/VSet | sed 's%src/%%;s%\.agda$%%;s%\.lagda.md$%%' | tr '/' . | grep -v '\.$' | sed 's/^/open import / >>src/VSet/All.agda'

module VSet.All where

open import VSet.Cat.Base
-- open import VSet.Construction.Monoidal
open import VSet.Data.Fin.Base
open import VSet.Data.Fin.Default
open import VSet.Data.Fin.Order
open import VSet.Data.Fin.Properties
open import VSet.Data.Fin.Splice
open import VSet.Data.Fin.Tests
open import VSet.Data.Fin
open import VSet.Data.HITTree.Base
open import VSet.Data.Inj.Base
open import VSet.Data.Inj.Order
open import VSet.Data.Inj.Properties
open import VSet.Data.Inj.Tests
open import VSet.Data.VecFun.Base
open import VSet.Data.VecFun.Properties
open import VSet.Data.VecFun.Tests
open import VSet.Data.Maybe
open import VSet.Data.Nat.Order
open import VSet.Data.Nat.Properties
open import VSet.Data.Nat.WellFounded
open import VSet.Data.Nat
open import VSet.Data.NatPlus.Base
open import VSet.Data.NatPlus.Properties
open import VSet.Data.SomeFin.Base
open import VSet.Data.SomeFin.Equality
open import VSet.Data.SomeFin.Injection
open import VSet.Data.SomeFin.Minus
open import VSet.Data.SomeFin.Properties
open import VSet.Data.Sum.Properties
open import VSet.Data.SumTree.Base
open import VSet.Data.SumTree.Metrics
open import VSet.Data.SumTree.WellFounded
open import VSet.Data.Tree.Base
open import VSet.Data.Tree.Properties
open import VSet.Function.Base
open import VSet.Function.Injection
open import VSet.Function.Iso
open import VSet.Function.Properties
open import VSet.Path
open import VSet.Prelude
open import VSet.Relation.Definitions
open import VSet.Relation.WellFounded.Base
open import VSet.Relation.WellFounded.Lex
open import VSet.Transform.Compose.Base
open import VSet.Transform.Compose.Properties
open import VSet.Transform.Compose.Tests
open import VSet.Transform.Elementary.Base
open import VSet.Transform.Elementary.Tests
open import VSet.Transform.Elementary.Properties
open import VSet.Transform.Inverse.Base
open import VSet.Transform.Inverse.Insert
open import VSet.Transform.Inverse.Properties
open import VSet.Transform.Inverse.Tests
open import VSet.Transform.SomeFin.Compose
open import VSet.Transform.SomeFin.Flatten
open import VSet.Transform.SomeFin.Inflate
open import VSet.Transform.SomeFin.Pred
open import VSet.Transform.SomeFin.Properties
open import VSet.Transform.SomeFin.Split
open import VSet.Transform.SomeFin.Sub
open import VSet.Transform.SomeFin.Tensor
open import VSet.Transform.SomeFin.Unused
open import VSet.Transform.Tensor.Associator
open import VSet.Transform.Tensor.Base
open import VSet.Transform.Tensor.Identity
open import VSet.Transform.Tensor.Properties
open import VSet.Transform.Trace.Base
open import VSet.Transform.Trace.Properties
open import VSet.Transform.Trace.Tests
